# Application
spring.application.name=virality-engine

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/virality_engine
spring.datasource.username=postgres
spring.datasource.password=995115
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080
